### ISSUE TITLE
Add new `liquid-c` headline benchmark

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit-bench#155]
This is a suggestion from Jimmy Miller. According to him, YJIT makes Liquid-C quite a bit faster, giving an extra boost above vanilla Liquid. That makes it worthwhile to track the performance of liquid-c, which will likely behave differently from vanilla liquid.

**Comment by eregon** [comment]
This can be closed, it was added in https://github.com/Shopify/yjit-bench/pull/170
