### ISSUE TITLE
Sequel YJIT regression

### ISSUE THREAD

**Issue by hmistry** [Shopify/yjit-bench#205]
Hi.

I'm curious - what is the reason for the recent regression in Sequel benchmarks where there is no speedup from YJIT?

**Comment by hmistry** [comment]
Ok, I noticed the slowdown back then and thought it was a temporary regression.

Not an issue because we're still on an older Ruby version. But would like to see there's some YJIT speedup and call some attention to it.

**Comment by k0kubun** [comment]
As Benoit said, #207 fixed the issue. Closing.
