### ISSUE TITLE
run_benchmarks.rb includes all data twice

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/yjit-bench#235]
We include unscaled data, then data multiplied by 1000 for milliseconds. It's confusing and wasteful. But I'm not sure if anybody's currently relying on it, so I'm loathe to just remove it quietly.

**Comment by eregon** [comment]
I already removed it in https://github.com/Shopify/yjit-bench/pull/229#issuecomment-1563001736
Also mentioned in https://github.com/Shopify/yjit-bench/pull/228#issuecomment-1529731670

**Comment by noahgibbs** [comment]
Interesting. So it shouldn't be showing up in latest main. I'll make sure I'm up to date and check again.
