### ISSUE TITLE
Better solution for running benchmarks once

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit-bench#28]
Often we want to run benchmarks for just a single iteration to gather some stats or test something.

Currently, our solution for this is ad-hoc. Some benchmarks like optcarrot and railsbench have a `run_once.rb` script, which duplicates some of the code in `benchmark.rb`. This is also problematic because not only does it duplicate code, but it's missing the logic for auto-installing dependencies in railsbench, for example.

Example:
https://github.com/Shopify/yjit-bench/blob/main/benchmarks/railsbench/run_once.rb

```
ruby --yjit-stats benchmarks/railsbench/run_once.rb
```

Maybe a better solution would be to have a run-once harness, so we can do something like:

```
ruby --yjit-stats -I./harness-once benchmarks/railsbench/benchmark.rb
```

@noahgibbs maybe you have an opinion on this ?

**Comment by eregon** [comment]
One way I used to do that is `WARMUP_ITRS=0 MIN_BENCH_ITRS=1 MIN_BENCH_TIME=0 ruby -I../.. benchmark.rb`.

**Comment by noahgibbs** [comment]
Benoit: yup, that works, and we could certainly use the existing harness with those settings. So we wouldn't necessarily have to change the harness -- or we could have the run-once harness wrap the existing harness code.

My first suggestion would be to have another top-level script, a "run_once" at the same level as run_benchmarks.rb. It could also be an option to run_benchmarks.rb, but I feel like run_benchmarks.rb is in pretty heavy need of refactoring right now. But an option to run_benchmarks.rb might be a quick fix before a larger solution.

The way I'm solving this problem in yjit-metrics is to have a pretty flexible harness, and then multiple top-level "runner" scripts that provide the parameters to the harness. I think it'd be easy enough to use the same approach in yjit-bench. I definitely wrote that harness intending that we could include it in yjit-bench, even if it's not there yet. Basically, yjit-metrics is a pretty comprehensive answer to the question of how I'd refactor run_benchmarks.rb :-)

**Comment by noahgibbs** [comment]
If we added a param to run_benchmarks.rb, it would wind up something like:

~~~
ruby run_benchmarks.rb --only-once yaml-load fannkuchredux
~~~

We could also add a shebang and do a "chmod +x" and optionally cut the "ruby" off the front :-)

**Comment by maximecb** [comment]
> One way I used to do that is WARMUP_ITRS=0 MIN_BENCH_ITRS=1 MIN_BENCH_TIME=0 ruby -I../../harness benchmark.rb.

Maybe we can turn this into a little shell script that sets the right environment variables.

> If we added a param to run_benchmarks.rb

I'll try the little shell script first because if we want to dump stats, for example, we don't want any Ruby code to run after the benchmark is done. I also find it nice to not try to stuff too many features into one script.

**Comment by noahgibbs** [comment]
Sure, a little shellscript sounds like a great temp fix. And longer-term, for the stats thing, we want the approach to stats used in yjit-metrics where the harness gathers just the stats that changed specifically during the benchmarking, not the whole process.

**Comment by maximecb** [comment]
It is using YJIT.

> Is it possible your script isn't loading chruby properly and you're losing the chruby to ruby-yjit?

I'm not sure what you mean by that.

Could this have to do with the changes you made to support older ruby versions / older bundler versions?

**Comment by noahgibbs** [comment]
If it's specifically in Railsbench, it could be related to those changes, yes. I didn't change anything in the yjit-bench harness, but I *did* change Railsbench's benchmark.rb, and specifically added the part at the front that tries to bundle install and migrate the DB.

> > Is it possible your script isn't loading chruby properly and you're losing the chruby to ruby-yjit?
>
> I'm not sure what you mean by that.

As an example, if you run `/bin/bash -c "chruby ruby-yjit"` the normal and expected result is for it to say that it doesn't recognise "chruby" as a command. That's because on an AWS host, chruby comes from a bash script that is often sourced in .bash_login (doesn't happen without the -l option to bash) or at the end of .bashrc (often not sourced to end in non-interactive shells, especially as the Ubuntu user). On a Shopify laptop it doesn't find chruby because /opt/dev/dev.sh in bash (but not zsh, weirdly) has a specific guard clause around it to only be sourced in interactive shells.

I *think* it'll usually keep running the appropriate Ruby version in most cases because environment variables are usually passed through. But if anything in .bashrc resets your PATH then it wouldn't.

**Comment by noahgibbs** [comment]
Huh. The specific gem it's complaining about, io-wait-0.1.1, is... Not actually a released gem: https://rubygems.org/gems/io-wait

Maybe there's a prerelease io-wait that's bundled into YJIT somehow but has no released equivalent on Rubygems? That would seem weird at first blush.

**Comment by noahgibbs** [comment]
The reason I asked if you were sure you were using YJIT is that there's a complaint message that's weird if you're using YJIT:

> Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.3.0.dev). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.3.0.dev --pre`.

The default version of Bundler in YJIT is 2.3.0.dev. 2.1.4 is the latest stable, and is what we usually install in older Rubies. So if it's giving that message then you're running an older Bundler. That's possible in YJIT, but it's mandatory in non-prerelease Rubies.

**Comment by noahgibbs** [comment]
If you'd like to pair on figuring this out, let me know. One difficulty with bash is how many things could be wrong here :-/

**Comment by noahgibbs** [comment]
Ah, and right now the main-branch railsbench/benchmark.rb has fixes, but not the latest proposed fixes. Which may also affect what you're seeing (or not.)

**Comment by noahgibbs** [comment]
The yjit-bench setup PR (https://github.com/Shopify/yjit-bench/pull/27) is ready to merge, yes.

**Comment by maximecb** [comment]
Ok cool. Could you resolve the conflict and merge it? :)

**Comment by noahgibbs** [comment]
Done.
