### ISSUE TITLE
The OptCarrot benchmark used in this repo leaks Fibers

### ISSUE THREAD

**Issue by eregon** [Shopify/yjit-bench#34]
I noticed the OptCarrot benchmark used in this repo does something quite unusual:
https://github.com/Shopify/yjit-bench/blob/6a2dd4a5ad3b653e9ce3c9d169b3b11d33b09e28/benchmarks/optcarrot/benchmark.rb#L4-L8

That creates a new `Optcarrot::NES` every time, and that also means it leaks one Fiber per instance/run.
CRuby has the feature/behavior/bug to hard kill (skip `ensure` code) Fibers when they are no longer reachable (not sure how reliable it is though), but that's in general not really feasible without native coroutines: https://github.com/oracle/truffleruby/issues/959#issuecomment-357229190
And it's a proper mess semantically-speaking.

I would suggest to either:
* Run OptCarrot as it meant to be (AFAIK), i.e., try to achieve >= 60 FPS, so reuse the same Optcarrot::NES instance and keep rendering more frames. The OptCarrot [README](https://github.com/mame/optcarrot/#benchmark-example) shows a 3000 frames plot to show peak performance. Lan_Master.nes has basically a consistent frames loop after some startup.
* Fix OptCarrot to actually dispose the [PPU Fiber](https://github.com/mame/optcarrot/blob/15def556c305d457d9b50f0a6ec9460fa1695ca1/lib/optcarrot/ppu.rb#L878) so the benchmark is more sensible to run with multiple Optcarrot::NES instances. That still means some extra IO etc (to load the cartridge) and maybe some other issues as the code seems not designed to be run like that.

**Comment by maximecb** [comment]
I wouldn't want to just run more frames because that's going to make the behavior different for every iteration of the benchmark. If there's an easy fix to kill the fibers we could merge that.

**Comment by eregon** [comment]
I see, that's a fair concern.

I'll see what's possible to release the PPU fiber, or to properly reset the NES.
There is NES#reset, and if that is reliable it would be one way to create a single NEW instance and avoid loading the cartridge every time, and avoid creating many Fibers during the benchmark.
Right now that doesn't reset `@frame` but that's trivial to add. I'll check if that works.

I was curious if the frames would follow some repeating pattern and actually I don't see any obvious repetition.
However, it's always the same 4 frames after startup (7-10), and there is only 10 different screens displayed (for 3000 frames):
https://gist.github.com/eregon/f80614e4435ff779585f3e65ac1bfa61

**Comment by eregon** [comment]
Resetting does not seem to work (the next time the PPU is onvoked it seems to loop forever).
Cleaning the PPU Fiber is actually than I thought: https://github.com/mame/optcarrot/pull/35
