### ISSUE TITLE
Add one `hexapdf` benchmark

### ISSUE THREAD

**Issue by maximecb** [Shopify/yjit-bench#46]
Apparently YJIT already shows speedups on this project, and it's open source. It's also "real-world" software that happens to not directly be a web use case. I was thinking that we could add just one of the larger benchmarks from their repository. Generally, longer-running benchmarks make for more accurate timing.

https://github.com/gettalong/hexapdf
https://github.com/gettalong/hexapdf/tree/master/benchmark

@noahgibbs would you be ok with taking this issue? I know you're busy with the upstreaming so this can wait. Otherwise we could ask Kevin or someone else on the team.

**Comment by noahgibbs** [comment]
I'm cool with taking this post-upstreaming. I'm also fine with somebody else doing it.

**Comment by maximecb** [comment]
A simple benchmark sounds good 👍
