### ISSUE TITLE
GraphQL benchmark

### ISSUE THREAD

**Issue by noahgibbs** [Shopify/yjit-bench#62]
GraphQL is important to Shopify. It's a good idea to have a benchmark for that.

**Comment by maximecb** [comment]
Good idea :)

**Comment by noahgibbs** [comment]
Realistically, I'm not going to get this done well before taking next week off. So I'll unassign this for now and pick it up in December if nobody else has.

Here's the GraphQL gem that most folks, including Shopify, use: https://github.com/rmosolgo/graphql-ruby

And here are their Getting Started docs: https://graphql-ruby.org/getting_started.html

The gem itself doesn't seem to have any runtime dependencies (https://github.com/rmosolgo/graphql-ruby/blob/master/graphql.gemspec), so it's probably reasonable to set up without Rails, even though their documentation starts with "run this Rails generator."

**Comment by maximecb** [comment]
Thank you for documenting this Noah 👌 

I hope you'll have a relaxing and enjoyable week off! 🌴 🙂

**Comment by noahgibbs** [comment]
I'm dropping this for now. The payoff is dubious since most large Rails apps, including Shopify's, don't seem to use much of the core GraphQL gem functionality for things like queries and serialisation, so this benchmark wouldn't be very representative. It would also be complicated to maintain, slightly more so than Railsbench. Not unreasonable for an important benchmark, but it makes an already-borderline benchmark less interesting.

**Comment by maximecb** [comment]
I trust your judgment 👍
